/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import useModelStore from "@/store/useStore";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

export function Rabbit2({ ...props }) {
  const { nodes, materials } = useGLTF("/models/rabbit.glb");
  const videoRef = useRef();

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]}></group>

      <mesh
        name="case"
        castShadow
        receiveShadow
        geometry={nodes["case"].geometry}
        material={materials.rabbit}
        material-wireframe={true}
      />
    </group>
  );
}

useGLTF.preload("/models/rabbit.glb");
